---
After:
  - framework/*
  - cms/*
---
StaticExporter:
  extensions:
    - DocumentationStaticPublisherExtension
  disable_sitetree_export: true
Controller:
  extensions:
    - ControllerExtension

---
After:
  - toolbar/*
---
GlobalNav:
  hostname: 'http://ssorg-another.test.silverstripe.com/'
  css_path: '/themes/ssv3/css/toolbar.css'
  use_localhost: false
SiteController:
  extensions:
    - GlobalNavExtension